# Generated by Django 4.1 on 2024-06-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prijavnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=100, null=True)),
                ("priimek", models.CharField(max_length=100, null=True)),
                ("email", models.CharField(max_length=100, null=True)),
                ("phone", models.CharField(max_length=15, null=True)),
                (
                    "dejavnost",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                (
                    "datumrojstva",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                ("valid", models.BooleanField(default=None, null=True)),
                ("komentar", models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
