# Generated by Django 4.1 on 2024-06-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_remove_prijavnica_komentar_remove_prijavnica_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="prijavnica",
            name="komentar",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="prijavnica",
            name="valid",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
